language: node_js

node_js:
  - 'node'

os:
  - windows
  - linux
  - osx

env:
  - BUILD_ENV=ci

branches:
  only:
    - master
    - test
    - /^greenkeeper/.*$/

install:
  - npm install

script:
  - npm run build
  - npm run test

after_success: npm run coverage
